apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotmart-deployment-v1
  labels:
    app: hotmart-deployment-v1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotmart
  template:
    metadata:
      labels:
        app: hotmart
    spec:
      containers:
        - name: hotmart
          image: hotmart:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: hotmart-configmap-v1
            - secretRef:
                name: hotmart-db-secret-v1
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3