services:
  mysql:
    container_name: 'mysql_hotmart'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE:-hotmart}'
      - 'MYSQL_USER=${MYSQL_USER:-admin}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD:-root}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}'
    ports:
      - '3306:3306'